import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { Check, ImagePlus, Mail, Pencil, Plus, Save, Trash2, UserRound, Users, X } from 'lucide-react'
import { supabase } from './lib/supabase'

const emptyContent = { news: [], teachers: [], classMembers: [], teacherSubjects: [] }
const formatDate = value => value ? new Intl.DateTimeFormat('vi-VN').format(new Date(value)) : '—'
const sortByOrder = (items) => [...items].sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0) || a.full_name.localeCompare(b.full_name, 'vi'))

export function useContent() {
  const [content, setContent] = useState(emptyContent)
  const [loading, setLoading] = useState(Boolean(supabase))
  const [error, setError] = useState('')
  useEffect(() => {
    if (!supabase) { setLoading(false); return undefined }
    let cancelled = false
    const load = async () => {
      const [newsResult, teachersResult, membersResult, linksResult] = await Promise.all([
        supabase.from('news').select('*').order('published_at', { ascending: false, nullsFirst: false }),
        supabase.from('teachers').select('*').order('sort_order').order('full_name'),
        supabase.from('class_members').select('*').order('sort_order').order('full_name'),
        supabase.from('teacher_subjects').select('*')
      ])
      if (cancelled) return
      const failures = [newsResult, teachersResult, membersResult, linksResult].filter(result => result.error)
      if (failures.length) setError('Một số nội dung mới chưa thể tải. Các chức năng khác vẫn hoạt động bình thường.')
      setContent({
        news: newsResult.error ? [] : newsResult.data || [],
        teachers: teachersResult.error ? [] : teachersResult.data || [],
        classMembers: membersResult.error ? [] : membersResult.data || [],
        teacherSubjects: linksResult.error ? [] : linksResult.data || []
      })
      setLoading(false)
    }
    load().catch(() => { if (!cancelled) { setError('Một số nội dung mới chưa thể tải.'); setLoading(false) } })
    return () => { cancelled = true }
  }, [])
  return { ...content, loading, error }
}

const publicImage = item => item.image_url || item.avatar_url || ''
function ImagePlaceholder({ label = 'Chưa có ảnh' }) { return <div className="content-image-placeholder"><ImagePlus size={24} /><span>{label}</span></div> }
function ImagePreview({ item, label }) { const image = publicImage(item); return image ? <img className="content-image" src={image} alt={item.title || item.full_name} /> : <ImagePlaceholder label={label} /> }

export function NewsPreview({ news }) {
  const item = news.find(entry => entry.published) || news[0]
  if (!item) return <section className="section news-feature"><div className="content-empty"><span className="eyebrow muted">BẢN TIN</span><p>Chưa có bản tin mới.</p></div></section>
  return <section className="section news-feature"><div className="news-feature-copy"><span className="eyebrow">BẢN TIN</span><h2>{item.title}</h2><time>{formatDate(item.published_at || item.created_at)}</time><p>{item.excerpt || item.content.slice(0, 150)}</p><Link className="text-link" to={`/news/${item.id}`}>Xem chi tiết <span aria-hidden="true">→</span></Link></div><Link className="news-feature-image" to={`/news/${item.id}`}><ImagePreview item={item} label="Chưa có ảnh bản tin" /></Link></section>
}
export function NewsPage({ news }) { const published = news.filter(item => item.published); return <main className="page-container"><div className="page-intro"><div><span className="eyebrow muted">CẬP NHẬT</span><h1>Bản tin</h1><p>Những thông báo và hoạt động mới nhất của lớp.</p></div></div>{published.length ? <div className="content-grid news-grid">{published.map(item => <article className="content-card" key={item.id}><Link to={`/news/${item.id}`}><ImagePreview item={item} label="Chưa có ảnh bản tin" /></Link><div className="content-card-body"><span className="eyebrow muted">BẢN TIN</span><h2><Link to={`/news/${item.id}`}>{item.title}</Link></h2><time>{formatDate(item.published_at || item.created_at)}</time><p>{item.excerpt}</p><Link className="text-link" to={`/news/${item.id}`}>Xem chi tiết →</Link></div></article>)}</div> : <div className="content-empty"><p>Chưa có bản tin mới.</p></div>}</main> }
export function NewsDetail({ news }) { const { id } = useParams(); const item = news.find(entry => entry.id === id && entry.published); if (!item) return <main className="page-container"><div className="content-empty"><p>Không tìm thấy bản tin.</p><Link className="text-link" to="/news">Quay lại bản tin</Link></div></main>; return <main className="page-container content-detail"><Link className="back-link" to="/news">← Bản tin</Link><span className="eyebrow muted">BẢN TIN</span><h1>{item.title}</h1><time>{formatDate(item.published_at || item.created_at)}</time><ImagePreview item={item} label="Chưa có ảnh bản tin" /><div className="content-body">{item.content.split(/\n\s*\n/).map((paragraph, index) => <p key={index}>{paragraph}</p>)}</div></main> }

const teacherSubjectsFor = (teacher, teacherSubjects, subjects) => teacherSubjects.filter(link => link.teacher_id === teacher.id).map(link => subjects.find(subject => subject.id === link.subject_id)?.name).filter(Boolean)
export function TeachersPage({ teachers, teacherSubjects, subjects }) { const visible = sortByOrder(teachers.filter(teacher => teacher.is_active)); return <main className="page-container"><div className="page-intro"><div><span className="eyebrow muted">ĐỘI NGŨ</span><h1>Thầy cô</h1><p>Thông tin các thầy cô và bộ môn phụ trách.</p></div></div>{visible.length ? <div className="content-grid people-grid">{visible.map(teacher => <article className="content-card person-card" key={teacher.id}><ImagePreview item={teacher} label="Chưa có ảnh" /><div className="content-card-body"><h2>{teacher.full_name}</h2><strong>{teacher.position}</strong><p>{teacher.department}</p>{teacherSubjectsFor(teacher, teacherSubjects, subjects).map(name => <span className="tag" key={name}>{name}</span>)}{teacher.show_email && teacher.email && <a className="contact-link" href={`mailto:${teacher.email}`}><Mail size={14} /> {teacher.email}</a>}{teacher.contact_url && <a className="text-link" href={teacher.contact_url} target="_blank" rel="noreferrer">Liên hệ →</a>}</div></article>)}</div> : <div className="content-empty"><p>Chưa có thông tin thầy cô.</p></div>}</main> }
export function ClassMembersPage({ classMembers }) { const visible = sortByOrder(classMembers.filter(member => member.is_active)); return <main className="page-container"><div className="page-intro"><div><span className="eyebrow muted">TẬP THỂ</span><h1>Danh sách lớp</h1><p>Cùng nhau học tập và phát triển.</p></div></div>{visible.length ? <div className="members-list">{visible.map((member, index) => <article className="member-row" key={member.id}><span className="member-number">{index + 1}</span><div className="member-avatar">{member.avatar_url ? <img src={member.avatar_url} alt={member.full_name} /> : <UserRound size={22} />}</div><div className="member-info"><h2>{member.full_name}</h2><span>{member.role}{member.student_code ? ` · ${member.student_code}` : ''}</span>{member.show_email && member.email && <a href={`mailto:${member.email}`}><Mail size={13} /> {member.email}</a>}{member.show_phone && member.phone && <span>{member.phone}</span>}</div></article>)}</div> : <div className="content-empty"><p>Chưa có danh sách lớp.</p></div>}</main> }

function useAdminCollection(table, initial) {
  const [items, setItems] = useState(initial)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const load = async () => { if (!supabase) return; setBusy(true); const { data, error: loadError } = await supabase.from(table).select('*').order(table === 'news' ? 'created_at' : 'sort_order', { ascending: false }); if (loadError) setError(loadError.message); else setItems(data || []); setBusy(false) }
  useEffect(() => { load() }, [table])
  return { items, setItems, error, setError, busy, setBusy, load }
}
const uploadImage = async (bucket, file) => { const extension = file.name.split('.').pop().toLowerCase(); const path = `${crypto.randomUUID()}.${extension}`; const { error } = await supabase.storage.from(bucket).upload(path, file, { contentType: file.type, upsert: false }); if (error) throw error; return { path, url: supabase.storage.from(bucket).getPublicUrl(path).data.publicUrl } }
const removeImage = async (bucket, path) => { if (path) await supabase.storage.from(bucket).remove([path]) }
function AdminShell({ title, children, error, action }) { return <><div className="admin-title-row"><div><span className="eyebrow muted">NỘI DUNG</span><h1>{title}</h1></div>{action}</div>{error && <div className="form-error">{error}</div>}{children}</> }
function ContentActions({ onEdit, onDelete }) { return <div className="row-actions"><button className="icon-button" title="Sửa" onClick={onEdit}><Pencil size={16} /></button><button className="icon-button danger" title="Xóa" onClick={onDelete}><Trash2 size={16} /></button></div> }

export function AdminNews() {
  const collection = useAdminCollection('news', []); const [editing, setEditing] = useState(null); const [form, setForm] = useState(null)
  const open = item => { setEditing(item); setForm(item || { title: '', excerpt: '', content: '', image_path: '', image_url: '', published: false, published_at: '' }) }
  const save = async event => { event.preventDefault(); collection.setError(''); collection.setBusy(true); try { const payload = { ...form, published_at: form.published ? (form.published_at || new Date().toISOString()) : null }; const { data, error } = editing ? await supabase.from('news').update(payload).eq('id', editing.id).select().single() : await supabase.from('news').insert(payload).select().single(); if (error) throw error; if (data) collection.setItems(current => editing ? current.map(item => item.id === editing.id ? data : item) : [data, ...current]); setForm(null); setEditing(null) } catch (error) { collection.setError(error.message) } finally { collection.setBusy(false) } }
  const remove = async item => { if (!window.confirm(`Xóa bản tin ${item.title}?`)) return; const { error } = await supabase.from('news').delete().eq('id', item.id); if (error) return collection.setError(error.message); await removeImage('news', item.image_path); collection.setItems(current => current.filter(entry => entry.id !== item.id)) }
  const image = async event => { const file = event.target.files?.[0]; if (!file) return; try { const uploaded = await uploadImage('news', file); setForm(current => ({ ...current, image_path: uploaded.path, image_url: uploaded.url })) } catch (error) { collection.setError(error.message) } }
  return <AdminShell title="Bản tin" error={collection.error} action={<button className="primary-button" onClick={() => open(null)}><Plus size={17} /> Thêm bản tin</button>}>{form && <NewsForm form={form} setForm={setForm} onImage={image} onCancel={() => setForm(null)} onSave={save} busy={collection.busy} /> }<div className="admin-table content-admin-table"><div className="table-head"><span>Bản tin</span><span>Trạng thái</span><span>Ngày đăng</span><span></span></div>{collection.items.map(item => <div className="table-row" key={item.id}><div className="table-subject"><div className="mini-content-image">{item.image_url ? <img src={item.image_url} alt="" /> : <ImagePlus size={16} />}</div><b>{item.title}</b></div><span className={item.published ? 'status active' : 'status hidden'}>{item.published ? 'Đã đăng' : 'Đang ẩn'}</span><span>{formatDate(item.published_at)}</span><ContentActions onEdit={() => open(item)} onDelete={() => remove(item)} /></div>)}</div></AdminShell>
}
function NewsForm({ form, setForm, onImage, onCancel, onSave, busy }) { return <form className="form-panel content-form" onSubmit={onSave}><div className="panel-heading"><h2>{form.id ? 'Sửa bản tin' : 'Thêm bản tin'}</h2><button type="button" className="icon-button" onClick={onCancel}><X size={18} /></button></div><div className="form-grid"><label>Tiêu đề<input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label>Ngày đăng<input type="datetime-local" value={form.published_at ? form.published_at.slice(0, 16) : ''} onChange={e => setForm({ ...form, published_at: e.target.value })} /></label><label className="wide">Mô tả ngắn<textarea value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} /></label><label className="wide">Nội dung<textarea required rows="8" value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.published} onChange={e => setForm({ ...form, published: e.target.checked })} /> Đăng bản tin</label></div><ImageUpload form={form} onImage={onImage} /><div className="form-actions"><button type="button" className="outline-button" onClick={onCancel}>Hủy</button><button className="primary-button" disabled={busy}><Save size={16} /> Lưu</button></div></form> }
function ImageUpload({ form, onImage }) { return <div className="image-upload"><div>{form.image_url ? <img src={form.image_url} alt="Preview" /> : <ImagePlaceholder label="Chọn ảnh" />}</div><label className="outline-button"><ImagePlus size={16} /> Upload ảnh<input type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={onImage} /></label></div> }

export function AdminTeachers({ subjects }) {
  const collection = useAdminCollection('teachers', []); const [editing, setEditing] = useState(null); const [form, setForm] = useState(null); const [links, setLinks] = useState([])
  useEffect(() => { supabase?.from('teacher_subjects').select('*').then(({ data }) => setLinks(data || [])) }, [])
  const open = item => setForm(item || { full_name: '', avatar_path: '', avatar_url: '', department: '', position: '', bio: '', email: '', contact_url: '', show_email: false, is_active: true, sort_order: 0, subject_ids: [] })
  const save = async event => { event.preventDefault(); collection.setBusy(true); try { const subjectIds = form.subject_ids || []; const payload = { ...form }; delete payload.subject_ids; delete payload.id; delete payload.created_at; delete payload.updated_at; const result = editing ? await supabase.from('teachers').update(payload).eq('id', editing.id).select().single() : await supabase.from('teachers').insert(payload).select().single(); if (result.error) throw result.error; const teacher = result.data; await supabase.from('teacher_subjects').delete().eq('teacher_id', teacher.id); if (subjectIds.length) { const { error } = await supabase.from('teacher_subjects').insert(subjectIds.map(subject_id => ({ teacher_id: teacher.id, subject_id }))); if (error) throw error } collection.setItems(current => editing ? current.map(item => item.id === editing.id ? teacher : item) : [teacher, ...current]); setForm(null); setEditing(null); await collection.load() } catch (error) { collection.setError(error.message) } finally { collection.setBusy(false) } }
  const remove = async item => { if (!window.confirm(`Xóa giáo viên ${item.full_name}?`)) return; const { error } = await supabase.from('teachers').delete().eq('id', item.id); if (error) return collection.setError(error.message); collection.setItems(current => current.filter(entry => entry.id !== item.id)) }
  const image = async event => { const file = event.target.files?.[0]; if (!file) return; try { const uploaded = await uploadImage('teachers', file); setForm(current => ({ ...current, avatar_path: uploaded.path, avatar_url: uploaded.url })) } catch (error) { collection.setError(error.message) } }
  const start = item => { setEditing(item); const subject_ids = links.filter(link => link.teacher_id === item?.id).map(link => link.subject_id); setForm(item ? { ...item, subject_ids } : null); if (!item) open(null) }
  return <AdminShell title="Thầy cô" error={collection.error} action={<button className="primary-button" onClick={() => start(null)}><Plus size={17} /> Thêm giáo viên</button>}>{form && <TeacherForm form={form} setForm={setForm} subjects={subjects} onImage={image} onCancel={() => setForm(null)} onSave={save} busy={collection.busy} /> }<div className="admin-table content-admin-table"><div className="table-head"><span>Họ tên</span><span>Bộ môn</span><span>Trạng thái</span><span></span></div>{collection.items.map(item => <div className="table-row" key={item.id}><div className="table-subject"><div className="mini-content-image">{item.avatar_url ? <img src={item.avatar_url} alt="" /> : <UserRound size={16} />}</div><b>{item.full_name}</b></div><span>{item.department}</span><span className={item.is_active ? 'status active' : 'status hidden'}>{item.is_active ? 'Hiển thị' : 'Ẩn'}</span><ContentActions onEdit={() => start(item)} onDelete={() => remove(item)} /></div>)}</div></AdminShell>
}
function TeacherForm({ form, setForm, subjects, onImage, onCancel, onSave, busy }) { const toggle = id => setForm({ ...form, subject_ids: form.subject_ids.includes(id) ? form.subject_ids.filter(item => item !== id) : [...form.subject_ids, id] }); return <form className="form-panel content-form" onSubmit={onSave}><div className="panel-heading"><h2>{form.id ? 'Sửa giáo viên' : 'Thêm giáo viên'}</h2><button type="button" className="icon-button" onClick={onCancel}><X size={18} /></button></div><div className="form-grid"><label>Họ tên<input required value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} /></label><label>Bộ môn<input value={form.department} onChange={e => setForm({ ...form, department: e.target.value })} /></label><label>Chức vụ<input value={form.position} onChange={e => setForm({ ...form, position: e.target.value })} /></label><label>Email<input type="email" value={form.email || ''} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Link liên hệ<input value={form.contact_url || ''} onChange={e => setForm({ ...form, contact_url: e.target.value })} /></label><label>Thứ tự<input type="number" value={form.sort_order} onChange={e => setForm({ ...form, sort_order: Number(e.target.value) })} /></label><label className="wide">Giới thiệu<textarea value={form.bio} onChange={e => setForm({ ...form, bio: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.show_email} onChange={e => setForm({ ...form, show_email: e.target.checked })} /> Công khai email</label><label className="checkbox-label"><input type="checkbox" checked={form.is_active} onChange={e => setForm({ ...form, is_active: e.target.checked })} /> Hiển thị</label></div><fieldset className="subject-checkboxes"><legend>Môn phụ trách</legend>{subjects.map(subject => <label key={subject.id}><input type="checkbox" checked={form.subject_ids.includes(subject.id)} onChange={() => toggle(subject.id)} /> {subject.name}</label>)}</fieldset><ImageUpload form={form} onImage={onImage} /><div className="form-actions"><button type="button" className="outline-button" onClick={onCancel}>Hủy</button><button className="primary-button" disabled={busy}><Save size={16} /> Lưu</button></div></form> }

export function AdminClassMembers() {
  const collection = useAdminCollection('class_members', []); const [form, setForm] = useState(null); const open = item => setForm(item || { full_name: '', avatar_path: '', avatar_url: '', student_code: '', role: 'Thành viên', sort_order: 0, email: '', phone: '', show_email: false, show_phone: false, is_active: true })
  const save = async event => { event.preventDefault(); collection.setBusy(true); const payload = { ...form }; delete payload.id; delete payload.created_at; delete payload.updated_at; const result = form.id ? await supabase.from('class_members').update(payload).eq('id', form.id).select().single() : await supabase.from('class_members').insert(payload).select().single(); if (result.error) collection.setError(result.error.message); else { collection.setItems(current => form.id ? current.map(item => item.id === form.id ? result.data : item) : [result.data, ...current]); setForm(null) } collection.setBusy(false) }
  const remove = async item => { if (!window.confirm(`Xóa thành viên ${item.full_name}?`)) return; const { error } = await supabase.from('class_members').delete().eq('id', item.id); if (error) return collection.setError(error.message); collection.setItems(current => current.filter(entry => entry.id !== item.id)) }
  const image = async event => { const file = event.target.files?.[0]; if (!file) return; try { const uploaded = await uploadImage('class-members', file); setForm(current => ({ ...current, avatar_path: uploaded.path, avatar_url: uploaded.url })) } catch (error) { collection.setError(error.message) } }
  return <AdminShell title="Danh sách lớp" error={collection.error} action={<button className="primary-button" onClick={() => open(null)}><Plus size={17} /> Thêm thành viên</button>}>{form && <MemberForm form={form} setForm={setForm} onImage={image} onCancel={() => setForm(null)} onSave={save} busy={collection.busy} /> }<div className="admin-table content-admin-table"><div className="table-head"><span>Thành viên</span><span>Vai trò</span><span>Công khai liên hệ</span><span></span></div>{collection.items.map(item => <div className="table-row" key={item.id}><div className="table-subject"><div className="mini-content-image">{item.avatar_url ? <img src={item.avatar_url} alt="" /> : <UserRound size={16} />}</div><b>{item.full_name}</b></div><span>{item.role}</span><span>{[item.show_email && 'Email', item.show_phone && 'SĐT'].filter(Boolean).join(', ') || 'Không'}</span><ContentActions onEdit={() => open(item)} onDelete={() => remove(item)} /></div>)}</div></AdminShell> }
function MemberForm({ form, setForm, onImage, onCancel, onSave, busy }) { return <form className="form-panel content-form" onSubmit={onSave}><div className="panel-heading"><h2>{form.id ? 'Sửa thành viên' : 'Thêm thành viên'}</h2><button type="button" className="icon-button" onClick={onCancel}><X size={18} /></button></div><div className="form-grid"><label>Họ tên<input required value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} /></label><label>Vai trò<input value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} /></label><label>Mã sinh viên<input value={form.student_code || ''} onChange={e => setForm({ ...form, student_code: e.target.value })} /></label><label>STT<input type="number" value={form.sort_order} onChange={e => setForm({ ...form, sort_order: Number(e.target.value) })} /></label><label>Email<input type="email" value={form.email || ''} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Số điện thoại<input value={form.phone || ''} onChange={e => setForm({ ...form, phone: e.target.value })} /></label><label className="checkbox-label"><input type="checkbox" checked={form.show_email} onChange={e => setForm({ ...form, show_email: e.target.checked })} /> Công khai email</label><label className="checkbox-label"><input type="checkbox" checked={form.show_phone} onChange={e => setForm({ ...form, show_phone: e.target.checked })} /> Công khai số điện thoại</label><label className="checkbox-label"><input type="checkbox" checked={form.is_active} onChange={e => setForm({ ...form, is_active: e.target.checked })} /> Hiển thị</label></div><ImageUpload form={form} onImage={onImage} /><div className="form-actions"><button type="button" className="outline-button" onClick={onCancel}>Hủy</button><button className="primary-button" disabled={busy}><Save size={16} /> Lưu</button></div></form> }

export function AdminContentNav() { return <><AdminLink to="/admin/news" label="Bản tin" icon={<Mail size={18} />} /><AdminLink to="/admin/teachers" label="Thầy cô" icon={<UserRound size={18} />} /><AdminLink to="/admin/class" label="Danh sách lớp" icon={<Users size={18} />} /></> }
function AdminLink({ to, label, icon }) { return <Link className="admin-content-link" to={to}>{icon}<span>{label}</span></Link> }
